remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: The STEM Career Paths Game
description: Informational page for an educational videogame about STEM Career paths
show_downloads: false
